spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_IP}${SPRING_DATASOURCE_DBNAME}${SPRING_DATASOURCE_SCHEAMA}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect