#Test enviroment (CI)
version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
      - ../src/main/resources/init-db/init.sql:/docker-entrypoint-initdb.d/data.sql
      - ./init/role.sh:/docker-entrypoint-initdb.d/role.sh
    environment:
      - POSTGRES_USER=${AUTHAPI_POSTGRES_USER}
      - POSTGRES_DB=auth
      - POSTGRES_PASSWORD=${AUTHAPI_POSTGRES_PASSWORD}
  spring-authentication-api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE=env
      - SPRING_DATASOURCE_IP=${AUTHAPI_POSTGRES_IP}
      - SPRING_DATASOURCE_DBNAME=${AUTHAPI_POSTGRES_DB}
      - SPRING_DATASOURCE_SCHEAMA=${AUTHAPI_POSTGRES_SCHEAMA}
      - SPRING_DATASOURCE_USERNAME=${AUTHAPI_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${AUTHAPI_POSTGRES_PASSWORD}
    depends_on:
      - postgres

volumes:
  psql-data: