CREATE TABLE TB_USER (
    uuid VARCHAR(36) PRIMARY KEY,
    user_code VARCHAR(17) UNIQUE NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    token_version integer NOT NULL,
    effective_password boolean NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE TB_ROLE (
    id integer PRIMARY KEY,
    name varchar(100) not null
);

CREATE VIEW V_USER AS
SELECT
USER_CODE,
email,
SUBSTRING(USER_CODE, LENGTH(USER_CODE ) - 16, 5) AS PREFIX,
SUBSTRING(USER_CODE, LENGTH(USER_CODE ) - 10, 5) AS INFIX,
SUBSTRING(USER_CODE, LENGTH(USER_CODE ) - 4, 5) AS SUFIX,
CAST(SUBSTRING(USER_CODE, LENGTH(USER_CODE ) - 16, 5) as int) AS PREFIX_CODE,
CAST(SUBSTRING(USER_CODE, LENGTH(USER_CODE ) - 10, 5) as int) AS INFIX_CODE,
CAST(SUBSTRING(USER_CODE, LENGTH(USER_CODE ) - 4, 5) as int) AS SUFIX_CODE
FROM TB_USER;

insert into TB_ROLE
select
0,
'ADMIN'
WHERE
NOT EXISTS (SELECT 1 from TB_ROLE where name='ADMIN');